feat: adding prop to datepicker for setting relative date range
tremorlabs/tremor-npm pull request #131
Opened 2022-10-20 11:56 UTC by jelleag

#130

2022-10-20 15:03 UTC, severinlandolt commented
Hey @jelleag, thank you for your constructive feedback. We will discuss your idea internally and get back to you soon.

2022-10-20 20:01 UTC, mitrotasios requested changes

2022-10-20 20:01 UTC, mitrotasios commented on src/components/input-elements/Datepicker/Datepicker.tsx
> +    relativeFilterOption?: 'w' | 't' | 'm' | 'y' | null,
I think this suggestion makes sense, thanks @jelleag! Would just recommend to call the prop `defaultRelativeFilterOption` to maintain consistency.

2022-10-20 20:01 UTC, mitrotasios commented on src/components/input-elements/Datepicker/Datepicker.tsx
> +    const [selectedRelativeFilterOption, setSelectedRelativeFilterOption] = useState<string | null>(
Let's also account for the case where `enableRelativeDates=false`. In that case users shouldn't be able to set a `defaultRelativeFilterOption` :)

2022-10-20 20:09 UTC, jelleag commented
Thanks for your comments! I've processed your suggestions in my latest commit

2022-10-20 20:12 UTC, mitrotasios commented
Awesome, thanks! that was fast :D I will work on some other bug fixes the next 1-2 days and then merge your PR over the weekend hopefully, because this will trigger a minor release :)

2022-10-27 19:49 UTC, mitrotasios approved these changes, later dismissed

2022-10-27 20:15 UTC, mitrotasios approved these changes

2022-10-27 20:16 UTC, merged