Expose d3-shape interpolation props
tremorlabs/tremor-npm pull request #409
Opened 2023-04-19 14:52 UTC by dani-z

Fixes #399

2023-04-22 07:44 UTC, mitrotasios requested changes
Thanks for the work! Just a minor change.

2023-04-22 07:44 UTC, mitrotasios commented on src/components/chart-elements/common/BaseChartProps.tsx
> +  curveType?: CurveType;
I wouldn't add the prop to the BaseChartProps as the interface is shared with the `BarChart` as well, which would not support a `curveType`

2023-04-23 09:13 UTC, dani-z commented on src/components/chart-elements/common/BaseChartProps.tsx
> +  curveType?: CurveType;
You're right, I just realised that those props are shared. I will amend the PR to only use this props for line and area charts.

2023-04-26 07:17 UTC, dani-z commented on src/components/chart-elements/common/BaseChartProps.tsx
> +  curveType?: CurveType;
Sorry for the delay @mitrotasios, I have updated the PR as suggested.

2023-04-26 21:46 UTC, mitrotasios commented on src/components/chart-elements/common/BaseChartProps.tsx
> +  curveType?: CurveType;
no worries, thanks a lot 🤗

2023-04-26 21:59 UTC, mitrotasios approved these changes

2023-04-26 22:06 UTC, merged

2023-05-01 21:15 UTC, dani-z commented
Hey @mitrotasios, thanks for merging. I've just seen that in the compiled code, the `CurveType` is wrongly typed, unfortunately :( 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/394966/235532600-4f9ccd1c-8b85-48b1-920f-244f843f8bd1.png">

However, the type does work, I am wondering if there's some naming conflict with the props?

2023-05-02 07:47 UTC, mitrotasios commented
hey @dani-z, that's right. We wanted to restrict the curveType to only contain one type for each category. We deemed the other available types such as `basisClosed` as unnecessary. Is there a specific type you're missing?

2023-05-02 20:17 UTC, dani-z commented
Yeah, I was looking for smooth edges, which is `monotone`

2023-05-03 15:56 UTC, mitrotasios commented
I see. The reason for restricting is that tremor currently aims at keeping things as simple as possible. In our opinion having one curve type for each category, i.e. "curved", linear and step, is enough as there is no real visual benefit in having different curved charts (e.g. monotone vs natural).

2023-05-06 16:15 UTC, dani-z commented
Sure, keeping things simple is a good decision. I am unsure, though, how exposing something that is already in the underneath layer would complicate it. But again, I appreciate your decision. 🙏