feat-Allow clear on selected daterange
tremorlabs/tremor-npm pull request #466
Opened 2023-05-17 16:39 UTC by Souravpakhira

2023-05-17 16:46 UTC, Souravpakhira commented
#321

2023-05-18 08:45 UTC, mitrotasios requested changes
Really great job, thanks! 🎉

Just have a minor suggestion :)

2023-05-18 08:45 UTC, mitrotasios commented on src/components/input-elements/DateRangePicker/DateRangePicker.tsx
> +  allowClear?: boolean;
lets call this `enableClear` 🙂

2023-05-18 08:53 UTC, mitrotasios requested changes

2023-05-18 08:53 UTC, mitrotasios commented on src/components/input-elements/DateRangePicker/DateRangePicker.tsx
> +    allowClear = false,
Oh and lets set this to `true` by default

2023-05-18 13:08 UTC, Souravpakhira commented on src/components/input-elements/DateRangePicker/DateRangePicker.tsx
> +  allowClear?: boolean;
Done as per the comment

2023-05-18 13:08 UTC, Souravpakhira commented on src/components/input-elements/DateRangePicker/DateRangePicker.tsx
> +    allowClear = false,
Done as per the suggestion

2023-05-18 16:12 UTC, mitrotasios approved these changes

2023-05-18 16:13 UTC, merged

2023-05-18 16:13 UTC, mitrotasios commented
Great Job 🥳

2023-05-18 16:14 UTC, Souravpakhira commented
> Great Job partying_face

Thanks excited to contribute more to this project